on:
  push:
    tags:
      - v*

env:
  REPOSITORY: morecontainers/stunnel
  TAG: ${{ github.ref_name }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build . -t $REPOSITORY:$TAG
      - run: docker push $REPOSITORY:$TAG
